services:
  # Backend API Service
  - type: web
    name: yandy-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run prisma:migrate && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: yandy-production-database
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: yandy-redis
          type: redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      - key: FRONTEND_URL
        value: https://yandybeautysalon.com
      - key: PORT
        value: 8000

  # Frontend Service (static site)
  - type: web
    name: yandy-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://yandy-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Redis
  - type: redis
    name: yandy-redis
    plan: free
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

# Database
databases:
  - name: yandy-production-database
    databaseName: yybeautysalon
    plan: free
    region: oregon
